spring:
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.10.51:3306/shedule?serverTimezone=UTC
    username: root
    password: 0WN3PGgqsJ!%
  flyway:
    baseline-on-migrate: true